
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from .views import *

urlpatterns = [
    path('',Homepage,name='Homepage'),
    path('signup/',signup,name='signup'),
    path('htmltutorials/',htmltutorials,name='htmltutorials'),
    path('htmltutorials/basictags',htmltutorialsbasictags,name='htmltutorials-basictags'),
    path('htmltutorials/textformatting',htmltutorialstextformatting,name='htmltutorials-textformatting'),
    path('htmltutorials/citationtags',htmltutorialscitationtags,name='htmltutorials-citationtags'),
    path('csstutorials/',csstutorials,name="csstutorials"),
    path('csstutorials/syntax',csstutorialssyntax,name='csstutorials-syntax'),
    path('csstutorials/selectors',csstutorialsselectors,name='csstutorials-selectors'),
    path('csstutorials/comments',csstutorialscomments,name='csstutorials-comments'),
    path('csstutorials/borders',csstutorialsborders,name='csstutorials-borders'),
    path('csstutorials/margins',csstutorialsmargins,name='csstutorials-margins'),
    path('csstutorials/boxmodel',csstutorialsboxmodel,name='csstutorials-boxmodel'),
    path('csstutorials/position',csstutorialsposition,name='csstutorials-position'),
    path('csstutorials/pseudoelements',csstutorialspseudoelements,name="csstutorials-pseudoelements"),
    path('csstutorials/transitions',csstutorialstransitions,name="csstutorials-transitions"),
    path('csstutorials/animations',csstutorialsanimations,name="csstutorials-animations"),
    path('jstutorials/',jstutorials,name="jstutorials"),
    path('jstutorials/output',jstutorialsoutput,name="jstutorials-output"),
    path('jstutorials/statements',jstutorialsstatements,name="jstutorials-statements"),
    path('jstutorials/syntax',jstutorialssyntax,name='jstutorials-syntax'),
    path('cssexamples/',cssexamples,name="cssexamples"),
    path('htmltutorials/lists',htmltutorialslists,name='htmltutorials-lists'),
    path('htmltutorials/tables',htmltutorialstables,name='htmltutorials-tables'),
    path('htmltutorials/blocklevel',htmltutorialsblocklevel,name='htmltutorials-blocklevel'),
    path('htmltutorials/inline',htmltutorialsinline,name='htmltutorials-inline'),
    path('htmltutorials/forms',htmltutorialsforms,name='htmltutorials-forms'),
    path('jstutorials/comments',jstutorialscomments,name="jstutorials-comments"),
    path('jstutorials/arithmetic',jstutorialsarithmetic,name="jstutorials-arithmetic"),
    path('jstutorials/functions',jstutorialsfunctions,name="jstutorials-functions"),
    path('jstutorials/arrays',jstutorialsarrays,name="jstutorials-arrays"),
    path('cssreferences/',cssreferences,name="cssreferences"),
    path('htmlexamples/',htmlexamples,name="htmlexamples"),
    path('htmlreferences/',htmlreferencesss,name="htmlreferences"),
    path('jsexamples/',jsexamples,name="jsexamples"),
    path('jsreferences/',jsreferences,name="jsreferences"),
    path('cssexercises/',cssex1,name="cssex1"),
    path('cssexercises2/',cssex2,name="cssex2"),
    path('cssexercises3/',cssex3,name="cssex3"),
    path('cssexercises4/',cssex4,name="cssex4"),
    path('cssexercises5/',cssex5,name="cssex5"),
    path('htmlexercises/',htmlex1,name="htmlex1"),
    path('htmlexercises2/',htmlex2,name="htmlex2"),
    path('htmlexercises3/',htmlex3,name="htmlex3"),
    path('htmlexercises4/',htmlex4,name="htmlex4"),
    path('htmlexercises5/',htmlex5,name="htmlex5"),
    path('jsexercises/',jsex1,name="jsex1"),
    path('jsexercises2/',jsex2,name="jsex2"),
    path('jsexercises3/',jsex3,name="jsex3"),
    path('jsexercises4/',jsex4,name="jsex4"),
    path('jsexercises5/',jsex5,name="jsex5"),
    path('onlinecompiler/',onlinecompiler,name="onlinecompiler"),
    path('certification/',certification,name="certification"),
]
